analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    inference_failure_on_function_invocation: ignore
    constant_identifier_names: ignore
    sort_constructors_first: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
