name: snapfood
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  build_verify: ^3.1.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.17
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.8.0
  go_router_builder: ^2.7.5
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  location: ^8.0.0
  meta: ^1.15.0
  phosphor_flutter: ^2.1.0
  riverpod_annotation: ^2.3.5
  shadcn_ui: ^0.20.2
  supabase_flutter: ^2.8.3
  url_launcher: ^6.2.5
  dio: ^5.8.0+1
  flutter_custom_tabs: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  riverpod_generator: 2.6.1
  riverpod_lint: ^2.6.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
